import { createHash } from "node:crypto";
import {
  COMPILER_NAME,
  COMPILER_VERSION,
  DESCRIPTOR_SCHEMA_VERSION,
  type ColorTokens,
  type CompilationResult,
  type ThemeDescriptor,
  type ThemeSpecification,
} from "./types.js";
import { validateThemeSpecification } from "./validator.js";

export function canonicalizeJson(obj: unknown): string {
  function sortKeys(val: unknown): unknown {
    if (val === null || typeof val !== "object") return val;
    if (Array.isArray(val)) return val.map(sortKeys);
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(val).sort((a, b) => a.localeCompare(b, "en"))) {
      sorted[key] = sortKeys((val as Record<string, unknown>)[key]);
    }
    return sorted;
  }
  return JSON.stringify(sortKeys(obj), null, 2) + "\n";
}

export function computeSha256(content: string | Uint8Array): string {
  return createHash("sha256").update(content).digest("hex");
}

function toCssVarName(role: string): string {
  // Convert camelCase to kebab-case
  return role.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function emitColorVariables(tokens: ColorTokens, indent = "  "): string {
  const lines: string[] = [];
  const entries = Object.entries(tokens).sort(([a], [b]) => a.localeCompare(b, "en"));
  for (const [key, value] of entries) {
    if (value !== undefined) {
      lines.push(`${indent}--${toCssVarName(key)}: ${value};`);
    }
  }
  return lines.join("\n");
}

export function compileTheme(input: unknown): CompilationResult {
  const validation = validateThemeSpecification(input);
  if (!validation.valid || !validation.specification) {
    throw new Error(`Theme validation failed:\n - ${validation.errors.join("\n - ")}`);
  }

  const spec = validation.specification;
  const canonicalJson = canonicalizeJson(spec);
  const inputDigest = computeSha256(canonicalJson);

  // 1. Build @theme inline block matching shadcn v4 oracle
  const themeInlineLines: string[] = [
    "@theme inline {",
    "  --font-sans: var(--font-sans);",
  ];

  if (spec.typography.fontHeading) {
    themeInlineLines.push("  --font-heading: var(--font-heading);");
  }
  if (spec.typography.fontMono) {
    themeInlineLines.push("  --font-mono: var(--font-mono);");
  }

  // Full radius progression matching shadcn v4 oracle
  themeInlineLines.push(
    "  --radius-sm: calc(var(--radius) * 0.6);",
    "  --radius-md: calc(var(--radius) * 0.8);",
    "  --radius-lg: var(--radius);",
    "  --radius-xl: calc(var(--radius) * 1.4);",
    "  --radius-2xl: calc(var(--radius) * 1.8);",
    "  --radius-3xl: calc(var(--radius) * 2.2);",
    "  --radius-4xl: calc(var(--radius) * 2.6);"
  );

  // Map semantic color roles to CSS variables
  const allRoles = new Set<string>([
    ...Object.keys(spec.palette.light),
    ...Object.keys(spec.palette.dark),
  ]);

  for (const role of [...allRoles].sort((a, b) => a.localeCompare(b, "en"))) {
    const varName = toCssVarName(role);
    themeInlineLines.push(`  --color-${varName}: var(--${varName});`);
  }

  themeInlineLines.push("}");

  // 2. Build :root (light mode) variables
  const rootLines: string[] = [
    ":root {",
    `  --radius: ${spec.surfaces.radius};`,
    `  --font-sans: ${spec.typography.fontSans};`,
  ];
  if (spec.typography.fontHeading) {
    rootLines.push(`  --font-heading: ${spec.typography.fontHeading};`);
  }
  if (spec.typography.fontMono) {
    rootLines.push(`  --font-mono: ${spec.typography.fontMono};`);
  }
  if (spec.surfaces.borderWidth) {
    rootLines.push(`  --border-width: ${spec.surfaces.borderWidth};`);
  }
  rootLines.push(emitColorVariables(spec.palette.light, "  "));
  rootLines.push("}");

  // 3. Build .dark, :root[data-theme='dark'] (dark mode) variables
  const darkLines: string[] = [
    ".dark, :root[data-theme='dark'] {",
    emitColorVariables(spec.palette.dark, "  "),
    "}",
  ];

  // 4. Combine into final stylesheet
  const css = [
    "/* Generated by Theme Forge Solar Sail — Tailwind CSS v4 & shadcn/ui application theme */",
    "@custom-variant dark (&:is(.dark *));",
    "",
    themeInlineLines.join("\n"),
    "",
    rootLines.join("\n"),
    "",
    darkLines.join("\n"),
    "",
  ].join("\n");

  const outputDigest = computeSha256(css);

  const descriptor: ThemeDescriptor = {
    schema: DESCRIPTOR_SCHEMA_VERSION,
    themeName: spec.name,
    themeVersion: spec.version,
    inputDigest,
    outputDigest,
    inventoryDigest: computeSha256(
      canonicalizeJson({
        inputDigest,
        outputDigest,
        name: spec.name,
        version: spec.version,
      })
    ),
    compiler: {
      name: COMPILER_NAME,
      version: COMPILER_VERSION,
    },
    diagnostics: validation.diagnostics,
    ...(spec.sourceProfileSha256 ? { sourceProfileSha256: spec.sourceProfileSha256 } : {}),
  };

  return {
    specification: spec,
    css,
    inputDigest,
    outputDigest,
    descriptor,
    diagnostics: validation.diagnostics,
    ...(spec.sourceProfileSha256 ? { sourceProfileSha256: spec.sourceProfileSha256 } : {}),
  };
}
